name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [10.*, 11.*, 12.*]
        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Laravel
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-update

      - name: Install Testbench
        run: |
          if [[ "${{ matrix.laravel }}" == 12.* ]]; then
            composer require orchestra/testbench:^10.0 --no-update
          elif [[ "${{ matrix.laravel }}" == 11.* ]]; then
            composer require orchestra/testbench:^9.0 --no-update
          else
            composer require orchestra/testbench:^8.0 --no-update
          fi

      - name: Install dependencies
        run: composer update -W --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit --colors=always --debug
